var menudata={children:[
{text:"Strona główna",url:"index.html"},
{text:"Przestrzenie nazw",url:"namespaces.html",children:[
{text:"Lista przestrzeni nazw",url:"namespaces.html"},
{text:"Składowe przestrzeni nazw",url:"namespacemembers.html",children:[
{text:"Wszystko",url:"namespacemembers.html"},
{text:"Funkcje",url:"namespacemembers_func.html"},
{text:"Definicje typów",url:"namespacemembers_type.html"},
{text:"Wyliczenia",url:"namespacemembers_enum.html"},
{text:"Wartości wyliczeń",url:"namespacemembers_eval.html"}]}]},
{text:"Klasy",url:"annotated.html",children:[
{text:"Lista klas",url:"annotated.html"},
{text:"Indeks klas",url:"classes.html"},
{text:"Hierarchia klas",url:"inherits.html"},
{text:"Składowe klas",url:"functions.html",children:[
{text:"Wszystko",url:"functions.html",children:[
{text:"_",url:"functions.html#index__"},
{text:"a",url:"functions_a.html#index_a"},
{text:"b",url:"functions_b.html#index_b"},
{text:"c",url:"functions_c.html#index_c"},
{text:"d",url:"functions_d.html#index_d"},
{text:"e",url:"functions_e.html#index_e"},
{text:"f",url:"functions_f.html#index_f"},
{text:"i",url:"functions_i.html#index_i"},
{text:"k",url:"functions_k.html#index_k"},
{text:"l",url:"functions_l.html#index_l"},
{text:"m",url:"functions_m.html#index_m"},
{text:"o",url:"functions_o.html#index_o"},
{text:"p",url:"functions_p.html#index_p"},
{text:"r",url:"functions_r.html#index_r"},
{text:"s",url:"functions_s.html#index_s"},
{text:"t",url:"functions_t.html#index_t"},
{text:"u",url:"functions_u.html#index_u"},
{text:"v",url:"functions_v.html#index_v"},
{text:"w",url:"functions_w.html#index_w"},
{text:"x",url:"functions_x.html#index_x"},
{text:"y",url:"functions_y.html#index_y"},
{text:"z",url:"functions_z.html#index_z"},
{text:"~",url:"functions_0x7e.html#index_0x7e"}]},
{text:"Funkcje",url:"functions_func.html",children:[
{text:"a",url:"functions_func.html#index_a"},
{text:"b",url:"functions_func.html#index_b"},
{text:"c",url:"functions_func.html#index_c"},
{text:"d",url:"functions_func.html#index_d"},
{text:"f",url:"functions_func.html#index_f"},
{text:"i",url:"functions_func.html#index_i"},
{text:"k",url:"functions_func.html#index_k"},
{text:"l",url:"functions_func.html#index_l"},
{text:"m",url:"functions_func.html#index_m"},
{text:"o",url:"functions_func.html#index_o"},
{text:"p",url:"functions_func.html#index_p"},
{text:"r",url:"functions_func.html#index_r"},
{text:"s",url:"functions_func.html#index_s"},
{text:"t",url:"functions_func.html#index_t"},
{text:"u",url:"functions_func.html#index_u"},
{text:"v",url:"functions_func.html#index_v"},
{text:"w",url:"functions_func.html#index_w"},
{text:"x",url:"functions_func.html#index_x"},
{text:"y",url:"functions_func.html#index_y"},
{text:"z",url:"functions_func.html#index_z"},
{text:"~",url:"functions_func.html#index_0x7e"}]},
{text:"Zmienne",url:"functions_vars.html",children:[
{text:"_",url:"functions_vars.html#index__"},
{text:"b",url:"functions_vars.html#index_b"},
{text:"c",url:"functions_vars.html#index_c"},
{text:"d",url:"functions_vars.html#index_d"},
{text:"e",url:"functions_vars.html#index_e"},
{text:"o",url:"functions_vars.html#index_o"},
{text:"r",url:"functions_vars.html#index_r"},
{text:"s",url:"functions_vars.html#index_s"},
{text:"t",url:"functions_vars.html#index_t"},
{text:"v",url:"functions_vars.html#index_v"},
{text:"x",url:"functions_vars.html#index_x"},
{text:"y",url:"functions_vars.html#index_y"}]},
{text:"Funkcje powiązane",url:"functions_rela.html"}]}]},
{text:"Pliki",url:"files.html",children:[
{text:"Lista plików",url:"files.html"},
{text:"Składowe plików",url:"globals.html",children:[
{text:"Wszystko",url:"globals.html",children:[
{text:"d",url:"globals.html#index_d"},
{text:"e",url:"globals.html#index_e"},
{text:"f",url:"globals.html#index_f"},
{text:"k",url:"globals.html#index_k"},
{text:"m",url:"globals.html#index_m"},
{text:"n",url:"globals.html#index_n"},
{text:"o",url:"globals.html#index_o"},
{text:"r",url:"globals.html#index_r"},
{text:"s",url:"globals.html#index_s"},
{text:"v",url:"globals.html#index_v"},
{text:"w",url:"globals.html#index_w"}]},
{text:"Funkcje",url:"globals_func.html"},
{text:"Zmienne",url:"globals_vars.html"},
{text:"Definicje typów",url:"globals_type.html"},
{text:"Wyliczenia",url:"globals_enum.html"},
{text:"Wartości wyliczeń",url:"globals_eval.html"},
{text:"Definicje",url:"globals_defs.html"}]}]}]}
